apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: otel-collector-config
  name: otel-collector-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
status: {}
